//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace BizContents
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignContent
    {
        public CampaignContent()
        {
            this.UserContents = new HashSet<UserContent>();
        }
    
        public int CampaignID { get; set; }
        public int ContentID { get; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> CreateDate { get; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> ActivationDate { get; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public bool UserContentInd { get; set; }
        public bool EmailNotificationInd { get; set; }
        public bool SMSNotificationInd { get; set; }
        public bool OSNotificationInd { get; set; }
        public string OSNotificationStatusDesc { get; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> OSNotificationSentDate { get; set; }
    
        public virtual Campaign Campaign { get; set; }
        public virtual ICollection<UserContent> UserContents { get; set; }
        public virtual Content Content { get; set; }
    }
}
