//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BizContents
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaign
    {
        public Campaign()
        {
            this.CampaignContents = new HashSet<CampaignContent>();
            this.CampaignMembers = new HashSet<CampaignMember>();
        }
    
        public int CampaignID { get; set; }
        public string CampaignDesc { get; set; }
        public Nullable<bool> CampaignActiveInd { get; set; }
        public string TargetPopulationDesc { get; set; }
        public string CampaignPeriodDesc { get; set; }
        public string TargetProcedureName { get; set; }
        public bool AuthRequiredInd { get; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> SavingsMonthStartDate { get; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual ICollection<CampaignContent> CampaignContents { get; set; }
        public virtual ICollection<CampaignMember> CampaignMembers { get; set; }
    }
}
