//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizContents
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentTypeState
    {
        public int ContentTypeID { get; set; }
        public int ContentStatusID { get; set; }
        public Nullable<bool> InitialStateInd { get; set; }
        public Nullable<bool> EndStateInd { get; set; }
        public string ContentStatusCaptionText { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual ContentStatu ContentStatu { get; set; }
        public virtual ContentType ContentType { get; set; }
    }
}
