//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BizContents
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public Content()
        {
            this.CampaignContents = new HashSet<CampaignContent>();
            this.UserContents = new HashSet<UserContent>();
            this.ContentTranslations = new HashSet<ContentTranslation>();
        }
    
        public int ContentID { get; set; }
        public int ContentTypeID { get; set; }
        public string ContentName { get; set; }
        public string ContentSourceDesc { get; set; }
        public string ContentImageFileName { get; set; }
        public string ContentFileLocationDesc { get; set; }
        public Nullable<int> ContentPointsCount { get; set; }
        public Nullable<int> ContentDurationSecondsCount { get; set; }
        public bool IntroContentInd { get; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ContentURL { get; set; }
        public string ContentPhoneNum { get; set; }
    
        public virtual ICollection<CampaignContent> CampaignContents { get; set; }
        public virtual Survey Survey { get; set; }
        public virtual ICollection<UserContent> UserContents { get; set; }
        public virtual ContentType ContentType { get; set; }
        public virtual ICollection<ContentTranslation> ContentTranslations { get; set; }
    }
}
