//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizContents
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CCH_CustomerDemoNCCTEntities : DbContext
    {
        public CCH_CustomerDemoNCCTEntities()
            : base("name=CCH_CustomerDemoNCCTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Campaign> Campaigns { get; set; }
        public virtual DbSet<CampaignContent> CampaignContents { get; set; }
        public virtual DbSet<CampaignMember> CampaignMembers { get; set; }
        public virtual DbSet<ClientConfig> ClientConfigs { get; set; }
        public virtual DbSet<Content> Contents { get; set; }
        public virtual DbSet<Survey> Surveys { get; set; }
        public virtual DbSet<SurveyQuestion> SurveyQuestions { get; set; }
        public virtual DbSet<UserContent> UserContents { get; set; }
        public virtual DbSet<ContentDisplayRule> ContentDisplayRules { get; set; }
        public virtual DbSet<ContentStatu> ContentStatus { get; set; }
        public virtual DbSet<ContentType> ContentTypes { get; set; }
        public virtual DbSet<ContentTypeState> ContentTypeStates { get; set; }
        public virtual DbSet<UserContentPreference> UserContentPreferences { get; set; }
        public virtual DbSet<Enrollment> Enrollments { get; set; }
        public virtual DbSet<ContentTranslation> ContentTranslations { get; set; }
        public virtual DbSet<Locale> Locales { get; set; }
    }
}
