//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizContents
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        public int CCHID { get; set; }
        public string EmployeeID { get; set; }
        public string MemberMedicalID { get; set; }
        public string MemberRXID { get; set; }
        public string SubscriberMedicalID { get; set; }
        public string SubscriberRXID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Middle { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string RelationshipCode { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
        public string Email { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public string UnRegisteredID { get; set; }
        public Nullable<bool> OptInIncentiveProgram { get; set; }
        public string Insurer { get; set; }
        public string RXProvider { get; set; }
        public string HealthPlanType { get; set; }
        public string MedicalPlanType { get; set; }
        public string RXPlanType { get; set; }
        public string Phone { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public Nullable<bool> OptInEmailAlerts { get; set; }
        public Nullable<bool> OptInTextMsgAlerts { get; set; }
        public string MobilePhone { get; set; }
        public Nullable<bool> OptInPriceConcierge { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string UpdateNotes { get; set; }
        public string MemberSSN { get; set; }
        public string SubscriberSSN { get; set; }
        public Nullable<int> Referral_CCHID { get; set; }
        public string MemberClassification { get; set; }
        public string Subscriber_Email_Home { get; set; }
        public string Subscriber_Email_Work { get; set; }
        public string Member_Email_Home { get; set; }
        public string Member_Email_Work { get; set; }
        public string Subscriber_Phone_Home { get; set; }
        public string Subscriber_Phone_Mobile { get; set; }
        public string Member_Phone_Home { get; set; }
        public string Member_Phone_Mobile { get; set; }
        public string Member_Status { get; set; }
        public string Interested_In_CCH { get; set; }
        public string Contract_Prefix { get; set; }
        public string Contract_Suffix { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> Subscriber_Coverage_Effective_Dt { get; set; }
        public Nullable<System.DateTime> Subscriber_Coverage_Termination_Dt { get; set; }
        public string Notes { get; set; }
        public string PropertyCode { get; set; }
        public string PCP_Name { get; set; }
        public string PCP_NPI { get; set; }
        public string HearCCH { get; set; }
        public string TandCIndicator { get; set; }
        public string Source_Phone { get; set; }
        public string Email_Phone { get; set; }
        public Nullable<System.DateTime> DateRegistered_Phone { get; set; }
        public string AlternatePlanSource { get; set; }
        public string MemberSSN_Full { get; set; }
        public Nullable<bool> PartialGeocode { get; set; }
        public Nullable<byte> RegistrationType { get; set; }
    }
}
