//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizContents
{
    using System;
    using System.Collections.Generic;
    
    public partial class Locale
    {
        public Locale()
        {
            this.ContentTranslations = new HashSet<ContentTranslation>();
            this.UserContentPreferences = new HashSet<UserContentPreference>();
        }
    
        public int LocaleID { get; set; }
        public string LocaleCode { get; set; }
        public string ISOCountryCode { get; set; }
        public string ISOLanguageCode { get; set; }
        public string LocaleDesc { get; set; }
        public string DateFormatDesc { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual ICollection<ContentTranslation> ContentTranslations { get; set; }
        public virtual ICollection<UserContentPreference> UserContentPreferences { get; set; }
    }
}
