//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BizContents
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserContent
    {
        public int CCHID { get; set; }
        public int CampaignID { get; set; }
        public int ContentID { get; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> ContentStatusChangeDate { get; set; }
        public string UserContentCommentText { get; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> NotificationSentDate { get; set; }
        public Nullable<decimal> ContentSavingsAmt { get; set; }
        public string MemberContentDataText { get; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> CreateDate { get; set; }
        public int ContentStatusID { get; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> SMSNotificationSentDate { get; set; }
        public string SMSNotificationStatusDesc { get; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> OSNotificationSentDate { get; set; }
        public string OSNotificationStatusDesc { get; set; }
    
        public virtual CampaignContent CampaignContent { get; set; }
        public virtual Content Content { get; set; }
        public virtual ContentStatu ContentStatu { get; set; }
    }
}
