//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizContents
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserContentPreference
    {
        public int CCHID { get; set; }
        public Nullable<bool> SMSInd { get; set; }
        public Nullable<bool> EmailInd { get; set; }
        public Nullable<bool> OSBasedAlertInd { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> DefaultLocaleID { get; set; }
        public string PreferredContactPhoneNum { get; set; }
    
        public virtual Locale Locale { get; set; }
    }
}
